version: '3.8'

services:
  backend:
    build:
      context: './back/todo'
    ports: 
      - "8083:8080"

  frontend:
    build:
      context: ./front
    ports:
      - "83:80"
    depends_on:
      - backend